---
all:
  children:
    controllers:
      hosts:
        osc:
          ansible_host: 10.121.1.20
    computes:
      hosts:
        osn1:
          ansible_host: 10.121.1.26
  vars:
    ansible_user: root
#    ansible_become: true
    ansible_become_pass: cisco
    ansible_python_interpreter: /usr/bin/python
#    ansible_ssh_pass: cisco
#    ansible_network_os: ios

