---
- name: Configure MariaDB on Centos 7
  hosts: controllers
  gather_facts: false

  tasks:

    - name: MARIADB>> Add Maria DB
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - mariadb
          - mariadb-server
          - python2-PyMySQL

    - name: MARIADB>> Create file /etc/my.cnf.d/openstack.cnf MariaDB
      template:
        src: "mariadb-openstack.j2"
        dest: /etc/my.cnf.d/openstack.cnf
        owner: root
        group: root
        mode: '0644'

    - name: MARIADB>> Enable services MariaDB and start
      systemd:
        name: mariadb
        enabled: yes
        state: started

    - name: MARIADB>> Set root Password
      mysql_user: 
        login_password: "{{ db_root_pass }}"
        check_implicit_admin: yes 
        append_privs: yes
        name: root 
        host: "{{ item }}"
        password: "{{ db_root_pass }}" 
        state: present 
        login_host: "{{ ansible_host }}"
      with_items:
        - localhost
        - 127.0.0.1
        - "{{ inventory_hostname }}"        
        # - "{{ controller.name }}"
        # - '%'

    - name: MARIADB>> Generate local file .mf.cnf
      template:
        src: "mysqldb_pass.j2"
        dest: "/root/.my.cnf"

